// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApA-oTjkWBNIdAoZfXAZQlaEhc_aoPdU4',
    appId: '1:237394199950:web:a9f0a4b3cfa51b554f90df',
    messagingSenderId: '237394199950',
    projectId: 'instagram-clone-6d18f',
    authDomain: 'instagram-clone-6d18f.firebaseapp.com',
    storageBucket: 'instagram-clone-6d18f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1m3oSbx-AWmM2tLMRGoimyndrM6dfM3Y',
    appId: '1:237394199950:android:f59861c960a7236b4f90df',
    messagingSenderId: '237394199950',
    projectId: 'instagram-clone-6d18f',
    storageBucket: 'instagram-clone-6d18f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9dULBHwbLx6PmX0hviCKjxuaR7cMYW-Q',
    appId: '1:237394199950:ios:2dfe9d2c5a08edb04f90df',
    messagingSenderId: '237394199950',
    projectId: 'instagram-clone-6d18f',
    storageBucket: 'instagram-clone-6d18f.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9dULBHwbLx6PmX0hviCKjxuaR7cMYW-Q',
    appId: '1:237394199950:ios:2dfe9d2c5a08edb04f90df',
    messagingSenderId: '237394199950',
    projectId: 'instagram-clone-6d18f',
    storageBucket: 'instagram-clone-6d18f.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApA-oTjkWBNIdAoZfXAZQlaEhc_aoPdU4',
    appId: '1:237394199950:web:ead91187f1ab802e4f90df',
    messagingSenderId: '237394199950',
    projectId: 'instagram-clone-6d18f',
    authDomain: 'instagram-clone-6d18f.firebaseapp.com',
    storageBucket: 'instagram-clone-6d18f.appspot.com',
  );
}
